package accountLedgerCli.toUtils.printMenu.commandLinePrintMenu.commandLinePrintMenuWithDefinedSeperatorAndDefinedPrompt.commandLinePrintMenuWithHyphenSeperatorAndDefinedPrompt.commandLinePrintMenuWithHyphenSeperatorDefinedPromptAndDefinedTitle

import accountLedgerCli.toUtils.printMenu.commandLinePrintMenu.commandLinePrintMenuWithDefinedSeperatorAndDefinedPrompt.commandLinePrintMenuWithHyphenSeperatorAndDefinedPrompt.CommandLinePrintMenuWithHyphenSeperatorAndDefinedPromptInterface

public interface CommandLinePrintMenuWithHyphenSeperatorDefinedPromptAndDefinedTitleInterface: CommandLinePrintMenuWithHyphenSeperatorAndDefinedPromptInterface {

    val title: String
    fun printMenuWithDefinedSeperatorDefinedPromptAndDefinedTitleFromListOfCommands(listOfCommands: List<String>) {
        printMenuWithDefinedSeperatorAndDefinedPromptFromListOfCommands(title, listOfCommands)
    }
}
