trigger:
  branches:
    exclude:
      - renovate/*

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: 'ubuntu-latest'

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  repositoryName: Account-Ledger-Cli-Kotlin-Gradle

steps:
  - checkout: self
    submodules: recursive

  - task: Cache@2.198.0
    inputs:
      key: 'gradle | "$(Agent.OS)"'
      restoreKeys: gradle
      path: $(GRADLE_USER_HOME)
    displayName: Gradle Build Cache

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '21'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - script: |
      sed -i "s|https://nomadller.in/http_api/|https://baneeishaque.helioho.st/GitHub_Banee-Ishaque_Account-Ledger-Server-PHP/http_API/|" account-ledger-lib/account-ledger-lib/src/main/kotlin/account/ledger/library/api/ApiConstants.kt
    displayName: "Inject secret serverApiAddress"

  - task: Gradle@3.208.0
    displayName: 'Gradle Build : Tar Distribution'
    inputs:
      gradleOptions: '-Xmx3072m'
      tasks: distTar

  - script: './gradlew --stop'
    displayName: Stop Gradle Daemon

  # TODO : If branch is not master : Extract folder, rename cli-app & cli-app.bat to Account-Ledger-CLI-$(Build.SourceName).bat, then repack as Account-Ledger-CLI-$(Build.SourceName).tar (Inner folders too); Otherwise Extract folder, rename cli-app & cli-app.bat to Account-Ledger-CLI.bat, then repack as Account-Ledger-CLI.tar (Inner folders too).

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        cd cli-app/build/distributions
        tar -xvf cli-app.tar
        mv cli-app Account-Ledger-Cli
        cd Account-Ledger-Cli/bin
        mv cli-app Account-Ledger-Cli
        chmod a+x Account-Ledger-Cli
        mv cli-app.bat Account-Ledger-Cli.bat
        echo -e "[tools]\njava = \"23.0.1\"" > mise.toml
        cd ../..
        tar -czvf Account-Ledger-Cli.tar.gz Account-Ledger-Cli
    displayName: Rebuilding Tar Distribution

  - publish: cli-app/build/distributions/Account-Ledger-Cli.tar.gz
    artifact: Account-Ledger-CLI
