/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
//allprojects {
//    repositories {
//        jcenter()
//    }
//}
//TODO : Customize distTar task to customize distribution file name
//TODO : Create windows, mac, linux, etc. installation files
//TODO : Include jre in distribution & executable files
