/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package transactionInserterForAccountLedger.cli.app

import kotlin.test.Test
import kotlin.test.assertEquals

class AppPropertiesTest {
    @Test
    fun testAppProperties() {
        assertEquals(AppProperties.appName, "Account Ledger CLI App")
        assertEquals(AppProperties.version, "0.0.1")
    }
}
