/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package transactionInserterForAccountLedger.cli.app

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppTest {
    @Test
    fun testAppProperties() {
        assertEquals(App.appName, "Sample CLI App")
        assertNotNull(App.version, "0.0.1")
    }
}
