package accountLedgerCli.enums

enum class BalanceSheetRefineLevelEnum {
    ALL, WITHOUT_OPEN_BALANCES, WITHOUT_MISC_INCOMES, WITHOUT_INVESTMENT_RETURNS, WITHOUT_FAMILY_ACCOUNTS, WITHOUT_EXPENSE_ACCOUNTS
}