package accountLedgerCli.enums

enum class EnvironmentFileEntryEnum {
    USER_NAME, PASSWORD, WALLET_ACCOUNT_ID, BANK_ACCOUNT_ID, FREQUENT_1_ACCOUNT_ID, FREQUENT_2_ACCOUNT_ID, FREQUENT_3_ACCOUNT_ID, FREQUENT_1_ACCOUNT_NAME, FREQUENT_2_ACCOUNT_NAME, FREQUENT_3_ACCOUNT_NAME, BANK_ACCOUNT_NAME, IS_DEVELOPMENT_MODE
}